name: CI Pipeline

on: [push]
    
jobs:
  build:    # job ID
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run a sample command
        run: echo "Hello from CI!"
